# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# Specify folder
install:
  - Rscript -e 'devtools::install_deps("project-4-L1-regularization/l1regularization")'
script:
  - Rscript -e 'devtools::check("project-4-L1-regularization/l1regularization/")'
