# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
 - cd project-4-L1-regularization/l1regularization/

# Specify folder
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat", "knitr"));devtools::install_deps()'
script:
  - Rscript -e 'devtools::check()'
